### ISSUE TITLE
Author Name Does not appear on Blog Post 

### ISSUE THREAD

**Issue by lealynfs** [mclag/mms142-groupg-2020#1]
On the Blog Post, the author name is not appearing on each blog post even if it was already added on the _cofig.yml. Please double check any bugs or what needs to change.

**Comment by mclag** [comment]
you used the wrong parameter in your md. under _config.yml, you set up your parameter as the following:
 
**Lea Lyn**:
    name: Lea Lyn Latawan
    display_name: Lea Lyn Latawan   
    avatar: 
    gravatar: 
    email: lmlatawan@up.edu.ph
    web:  https://github.com/lealynfs
    twitter:
    description: UPOU BAMS Student

therefore your author value in your blog post should be 'Lea Lyn'
